### ISSUE TITLE
Music shield plugin makes the whole system fail

### ISSUE THREAD

**Issue by volumio** [petecallaghan/volumio-plugins#22]
@petecallaghan please can you fix the plugin ASAP?
It makes the whole system fail.

Two suggestions:
- Do not place anything in the onVolumioStart function, but put all on the onStart
- Always use try catch when you execute

This is a report:
https://github.com/volumio/Volumio2-UI/issues/801

To me, the issue starts at https://github.com/volumio/volumio-plugins/blob/b68938b929424e09796d61973af5220ea94e1a36/plugins/miscellanea/music_services_shield/index.js#L69

**Comment by petecallaghan** [comment]
Duplicates https://github.com/petecallaghan/volumio-plugins/issues/23
